### ISSUE TITLE
Changing Control - Aircraft starts to dive without able to recover

### ISSUE THREAD

**Issue by fresH229a** [D1ngtalk/Yourcontrols-config-for-Fenixsim-A320#7]
Hey there,

first of all, THANKS for this really great work you do! 
Waiting long for a possibility to Share my Fenix Cockpit :)

One thing we recognized is, when changing the Control, the Aircraft starts to dive extremly without a possibility to recover.
I am not sure if you can do something about this problem.

I am not sure what happend if you put the FLT CTRLs stuff under the shared vars in the config file.
Probably this would make an "give control" obsolet cause they are shared anyway all the time.

Thanks!

**Comment by D1ngtalk** [comment]
This is an existing problem, because of the auto trim value is in the Fenix external software, have not any variables in simulator. So we can't sync both side's auto trim value through Yourcontrol. To avoid this problem, DO NOT  transfer control when you airborne, if you still need transfer control, trun off two ELAC to make MAN PITCH TRIM ONLY, and transfer control.

**Comment by D1ngtalk** [comment]
I will try to fix this problem with Fenix and Yourcontrol team. But i have no idea now, so I will mark this issue as close. thanks for you comment.
